spring:
  application:
    name: springai_chat

      # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${API_KEY}
      chat:
        options:
          model: qwen-plus
          temperature: 0.7

      embedding: #向量模型配置
        options:
          model: text-embedding-v4 #向量模型名
          dimensions: 1024  #向量维度，模型有默认值，可以不配置




    vectorstore:
      redis:
        index-name: Spring_ai_index  #向量数据库索引名
        initialize-schema: true   #首次启动，是否自动建索引
        prefix: "doc"  #向量数据库key前缀



  data: #Redis数据库配置
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/springai_chat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: LHP20040302
    driver-class-name: com.mysql.cj.jdbc.Driver

# 修改为MyBatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.springai_chat.entity.po

logging:
  level:
    org.springframework.ai: debug
    com.example.springai: debug


# 阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com  # 根据你的region调整
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: springai-chat
    



